spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: anime-service
  datasource:
    url: jdbc:mysql://${ENV_MYSQL_HOST:localhost}:3306/anime_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_MYSQL_ROOT_USER:root}
    password: ${ENV_MYSQL_ROOT_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
server:
  port: 8080
  tomcat:
    threads:
      max: 20
